// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import ()

type Agent struct {
	AgentId     int32
	FirstName   string
	LastName    string
	Phone       int16
	Email       string
	Password    string
	Photo       string
	Description string
}
