// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type CreateAgentInput struct {
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Phone       int    `json:"phone"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	Photo       string `json:"photo"`
	Description string `json:"description"`
}

type CreatePropertyInput struct {
	Address     string `json:"address"`
	Status      string `json:"status"`
	Rooms       int    `json:"rooms"`
	Toilets     int    `json:"toilets"`
	Park        int    `json:"park"`
	Size        int    `json:"size"`
	Description string `json:"description"`
	Features    string `json:"features"`
	AgentID     int    `json:"agent_id"`
}

type UpdateAgenInput struct {
	AgentID     int    `json:"agent_id"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Phone       int    `json:"phone"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	Photo       string `json:"photo"`
	Description string `json:"description"`
}

type UpdatePropertyInput struct {
	PropertyID  int    `json:"property_id"`
	Address     string `json:"address"`
	Status      string `json:"status"`
	Rooms       int    `json:"rooms"`
	Toilets     int    `json:"toilets"`
	Park        int    `json:"park"`
	Size        int    `json:"size"`
	Description string `json:"description"`
	Features    string `json:"features"`
	AgentID     int    `json:"agent_id"`
}

type UploadPhotoInput struct {
	PropertyID int            `json:"property_id"`
	File       graphql.Upload `json:"file"`
}
